### ISSUE TITLE
Multiple Checkbox default value issue

### ISSUE THREAD

**Issue by mangz007** [Holt59/cakephp3-bootstrap-helpers#116] opened 2017-03-09 18:34 UTC
I am having issue in checking default value in multiple checkbox. I am using this:

```php
$options = [0 => 'something', 1 => 'first item', 2 => 'second item', 3 => 'third item'];
$this->Form->input('field', [
    'options' => $options, 
    'multiple' => 'checkbox', 
    'default' => [1,3]
]);
```

I am using **CakePHP 3.3.15**.

**Comment by Holt59** [comment] 2017-03-10 09:37
I cannot reproduce with CakePHP 3.3.15 and the version 3.1.1 of this plugin:

```php
$options = [0 => 'something', 1 => 'first item', 2 => 'second item', 3 => 'third item'];
echo $this->Form->input('field', [
    'options' => $options, 
    'multiple' => 'checkbox', 
    'default' => [1,3]
]); 
```

Output:
```html
<div class="form-group select">
  <label class="control-label"  for="field">Field</label>
  <input type="hidden" name="field" class="form-control"  value="" />
  <div class="checkbox">
    <label for="field-0">
      <input type="checkbox" name="field[]" value="0" id="field-0">something
    </label>
  </div>
  <div class="checkbox">
    <label for="field-1" class="selected">
      <input type="checkbox" name="field[]" value="1" checked="checked" id="field-1">first item
    </label>
  </div>
  <div class="checkbox">
    <label for="field-2"><input type="checkbox" name="field[]" value="2" id="field-2">second item
    </label>
  </div>
  <div class="checkbox">
    <label for="field-3" class="selected">
      <input type="checkbox" name="field[]" value="3" checked="checked" id="field-3">third item
    </label>
  </div>
</div>
```

**Comment by Holt59** [comment] 2017-03-19 08:52
Closing this, feel free to re-open this issue or a new one if you still have troubles.

**Closed by Holt59** 2017-03-19 08:52 UTC
Labels: form-helper
