### ISSUE TITLE
UrlComparerTrait::_normalize throws

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap-helpers#107] opened 2017-02-14 15:14 UTC
When upgrading to 3.1 and using the `BootstrapNavbarHelper` a `MissingRouteException` will be thrown from `RouteCollection::parse`, originating from `BootstrapNavbarHelper::_normalize`. The error message is "A route matching "/http://localhost/test" could not be found." (note the slash at front!)

This is likely due to the changes to `RouteCollection::parse` in CakePHP 3.4.

Test code:
```php
$nav = $this->BootstrapNavbar;
echo $nav->beginMenu();
echo $nav->link('Test', ['controller' => 'Test', 'action' => 'index']);
echo $nav->end();
```

I'm using CakePHP 3.4 and Bootstrap Helpers 3.1.

A simple fix is to disable automatic link activation:
```php
$this->BootstrapNavbar->config('autoActiveLink', false);
```

**Comment by Holt59** [comment] 2017-02-14 16:14
Which version of CakePHP are you using? 

Actually, I don't really understand the issue since `/https://example.com/test` is not a valid URL anyway, isn't it?

**Comment by nrother** [comment] 2017-02-14 18:09
Sorry, my original bug report was really bad (I was kinda in a rush...). I updated the issue with more information.

**Comment by Holt59** [comment] 2017-02-14 18:17
I will test this with a complete CakePHP installation when I get one, currently it seems to work in my test cases. 

- Could you show me the relevant part of your `config/routes.php`?
- Do you use the latest CakePHP 3.4 version (released 2 days ago)?

**Comment by nrother** [comment] 2017-02-14 18:37
This is from my `routes.php` (nothing special...)
```php
$routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
$routes->connect('/register', ['controller' => 'Registrations', 'action' => 'selectProject']);
$routes->connect('/register/*', ['controller' => 'Registrations', 'action' => 'registerForProject']);
$routes->connect('/impressum', ['controller' => 'Pages', 'action' => 'display', 'imprint']);
$routes->connect('/confirmations/anmeldebestätigung_:id', ['controller' => 'Registrations', 'action' => 'getConfirmation'], ['pass' => ['id'], 'id' => '[0-9]+']);

$routes->connect('/admin', ['controller' => 'Pages', 'action' => 'display', 'prefix' => 'admin', 'home']);
```
Yes, I'm using the latest version (updated today).

Cake did change something in `Route::parse`, and for me it looks like for some reason a slash is prepended to the URL which confuses the following code. I also had some problems updating my own code...

**Comment by Holt59** [comment] 2017-02-14 20:12
Should be fixed by 0f9d9bf, I have retro-added it to 3.1.0... This may still have issue with strange URLs, but should work pretty well for "standard" urls.

**Comment by nrother** [comment] 2017-02-15 12:51
Yes, it works now. 

Please note that composer hasn't noticed the retro-added commit, I had to remove and reinstall the package to make it see the update.

**Comment by nrother** [comment] 2017-02-15 13:32
Ok, the fix did not completely resolve the issue, now _every_ link is marked as active :smile: Maybe `_normalize()` is confused when the URL contains prefixes and/or is not in the base directory?

Example: 
```php
//Before normalize:
$lhs = '/chell/admin/rights';
$rhs = '/chell/admin/users/edit/1';
//After _normalize():
$lhs = '/chell/admin/chell/admin';
$rhs = '/chell/admin/chell/admin';
```
The URLs are in the `admin` prefix and my app is running under  `localhost/chell`.

**Comment by Holt59** [comment] 2017-02-15 18:15
The problem is that `Router::url('/chell/admin/rights')` returns `'/chell/chell/admin/rights`... The `Router` class of CakePHP is such a mess to me, it is really hard to work with...

As a temporary fix, could you not simply pass URL without the `chell` prefix to the Navbar helper? Such as:

```php
$this->navbar->link('...', ['controller' => 'rights', 'action' => 'index', 'admin' => true]);
```

**Comment by Holt59** [comment] 2017-02-15 18:49
I tried a fix which is now available on `dev-master`, `v3.1.0` and `v3.1.2`. I do not have a lot of time to work on a really strong set of tests, but I will try to strengthen the current ones when I have.

**Comment by nrother** [comment] 2017-02-16 10:05
`dev-master` has currently set CakePHP < 3.4.0 as a requirement. Using v.3.2.1.x-dev throws an exception:
```
The "Html" alias has already been loaded with the following config: array (...) which differs from array ( 'className' => 'Bootstrap.Html', ) 
```

**Comment by Holt59** [comment] 2017-02-16 13:30
When is this exception thrown? Could you show me the code where you load the helpers?

I have changed the names of the helpers in v3.2.1 (`Bootstrap.BootstrapHtmlHelper` -> `Bootstrap.HtmlHelper`), but the old names are still there for compatibility so this should not be an issue...

**Comment by Holt59** [comment] 2017-02-16 20:51
After a bit of testing, this seems to happens if you load the `Bootstrap.HtmlHelper` twice, but with different configs, e.g.:

```php
// In your AppController
public $helpers = [
    'Html' => [
        'className' => 'Bootstrap.BootstrapHtml'
    ]
];

// In your AppView
public function initialize() {
    $this->loadHelper('Html', [
        'className' => 'Bootstrap.Html'
    ]);
}
```

I don't think it is directly related to the helpers... Did you modify anything related to the names of the helpers?

**Comment by Holt59** [comment] 2017-02-16 20:54
We can discuss this error in #109 since this is not related to the `UrlComparerTrait` anymore.

**Comment by Holt59** [comment] 2017-02-20 07:15
Should be fixed by now, you can check the new documentation for the exact behavior:

http://holt59.github.io/cakephp3-bootstrap-helpers/navbar-helper/auto-active-link/

I am closing this, feel free to (re-)open if you still have troubles ;)

**Closed by Holt59** 2017-02-20 07:15 UTC
Labels: bug, confirmed, url-comparer-trait
