### ISSUE TITLE
FormHelper template for labelLegendHorizontal uses `legend`-tag instead of `label`-tag

### ISSUE THREAD

**Issue by mimaoffice** [Holt59/cakephp3-bootstrap-helpers#165] opened 2018-10-17 15:18 UTC
* [x] bug?
* [x] question

* CakePHP Version: 3.6.12
* Plugin Version/Branch: dev-4.0.1-alpha

I'm using this code:

    <?= $this->Form->control('bill_amount') ?> 
    <?= $this->Form->control('bill_date') ?> 

The first label is rendered using a `label`-tag and the second on using a `legend`-tag and in Bootstrap's CSS the font size for the legend is bigger than the one of label.

On the other side, the template for `labelLegend` is done using the `label`-tag.

In my own opinion the template for `labelLegendHorizontal` should also use the `label`-tag, like this:

    'labelLegendHorizontal' => '<label class="col-form-legend {{labelColumnClass}}{{attrs.class}}"{{attrs}}>{{text}}</label>'

Bests,
Michele

**Comment by Holt59** [comment] 2018-10-20 18:59
Thanks for the feedback. The problem is not the tag itself but the `col-form-legend` which was in one of the first bootstrap release. This should be changed to `col-form-label`.

**Comment by Holt59** [comment] 2018-10-24 17:31
Should be fixed by fed5735ebfb8b338b77c952a565654c1753299a0.

**Closed** 2018-11-25 14:54 UTC
Labels: bug, form-helper
