### ISSUE TITLE
Failed to install on cakephp 3.5.x

### ISSUE THREAD

**Issue by welemski** [Holt59/cakephp3-bootstrap-helpers#143] opened 2017-12-01 18:16 UTC
Recently updated CakePHP to 3.5.x

Below is the result when install dev-master
```bash
$ composer require holt59/cakephp3-bootstrap-helpers
Using version ^3.1 for holt59/cakephp3-bootstrap-helpers
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for holt59/cakephp3-bootstrap-helpers ^3.1 -> satisfiable by holt59/cakephp3-bootstrap-helpers[v3.1.0].
    - holt59/cakephp3-bootstrap-helpers v3.1.0 requires cakephp/cakephp >=3.2.3, <3.4.0 -> satisfiable by cakephp/cakephp[3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.0-RC1, 3.3.0-beta, 3.3.0-beta2, 3.3.0-beta3, 3.3.1, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.16, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

Below is the log when installing v3.1.2.x-dev
```bash
Package holt59/cakephp3-bootstrap-helpers at version v3.1.2.x-dev has a PHP requirement incompatible with your PHP version (7.1.4.0)                                                                                                                            
```

**Comment by Holt59** [comment] 2017-12-01 20:56
The issue with `3.1.0` is expected, there are breaking changes in CakePHP 3.4.

I cannot reproduce the issue with 3.1.2 though... Could you provide more details on your configuration? I tried a clean install in a docker container with PHP 7.1.4 and did not encounter any problem.

**Comment by Holt59** [comment] 2018-04-19 16:44
Closing this. If you still have troubles, feel free to add a comment a re-open it, or open a new issue if you face a different problem.

**Closed by Holt59** 2018-04-19 16:44 UTC
