### ISSUE TITLE
Add support for panels

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap-helpers#68] opened 2016-01-21 13:33 UTC
Support for panels would be nice: http://getbootstrap.com/components/#panels

(Support for collapsable panels would be even better!). These require a similar big amount of markup as modals, so support in the helper would be great!

**Comment by Holt59** [comment] 2016-01-21 14:06
Feel free to have a look at the [`panel-helper`](https://github.com/Holt59/cakephp3-bootstrap-helpers/tree/panel-helper) branch.

I will try to add collapsible panel if possible.

**Comment by ypnos-web** [comment] 2016-02-18 16:30
I am using that for a while, maybe you want to merge with master before adding collapsible?

**Comment by Holt59** [comment] 2016-02-18 18:21
I have just merge the branch, will try to work on the collapsible panels when I have time.

**Comment by Holt59** [comment] 2016-02-21 17:16
I have added options for collapsible panels in the `panel-helper` branch, feel free to test it. You can either specify `['collapsible' => true]` as an option to `create` or use group:
```php
echo $this->Panel->startGroup();

echo $this->Panel->create('This is the first panel');
echo "A bit of HTML code inside!";

echo $this->Panel->create('This is the second panel');
echo "A bit of HTML code inside!";

echo $this->Panel->create('This is the third panel');
echo "A bit of HTML code inside!";

echo $this->Panel->endGroup();
```

You can specify which panel should be open by default using the `open` option which must be an integer (panel count start at 1). Set it to `false` to leave all panels closed.

**Comment by nrother** [comment] 2016-03-21 17:29
Just testing the new Panel module, seems to work great a the first look.

A quick bug report:

```php
if (is_array($title)) {
            $title   = null;
            $options = $title;
        }
```
That is probably not so smart, `$options` will always be `null`:smile:

**Comment by Holt59** [comment] 2016-03-21 17:47
@nrother Thanks, this should be fixed by 38e81d86e2cb4604ba3493495c3cd16846bb82d2.

**Comment by nrother** [comment] 2016-03-21 17:56
Perfect, thanks.

How do collapsible panels work? This code just adds a link to the title which does nothing:
```php
echo $this->Panel->create('test', ['collapsible' => true]);
```

**Comment by Holt59** [comment] 2016-03-21 18:01
The following works for me:

````php
echo $this->Panel->create('This is a panel', ['collapsible' => true]);
echo "A bit of HTML code inside!";
echo $this->Panel->end();
```

Are  you sure to have the correct jquery and bootstrap javascript files?

To create groups, see my previous comments.

**Comment by nrother** [comment] 2016-03-30 14:17
Ok, it worked already. I just had a panel with a table as "body" (direct, not wrapped inside the body-section to make it seamless), and that is obviously not collapsed.

Slight bug: When creating a collapsible panel, the title is escaped, while normally it's not. This also breaks easy-icons in titles. (Due to the call to `HtmlHelper::link` in [L194](https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/master/src/View/Helper/BootstrapPanelHelper.php#L194))

**Comment by nrother** [comment] 2016-03-30 14:37
Next question (I know, this is not really a Q&A, sorry): Is there a way to make panels collapsed by default?

**Comment by Holt59** [comment] 2016-03-31 17:27
Escaping in header should be fixed by latest commits. For the default collapsible it is not currently possible but should not be to hard to implement using the config trait.

**Comment by Holt59** [comment] 2016-04-01 09:32
Actually, I think I misunderstood your last question. I have added a way to make panel **collapsible** by default using, e.g.:

```php
$this->loadHelper('Panel', [
    'collapsible' => true
]);
// or...
$this->Panel->config('collapsible', true);
```

Not that setting `'collapsible'` inside a panel group is not defined, the value will be reset at the end.

But I think that what you want was to have **collapsed** panel... I fixed a bug with commit b1cbd831237e4c9da73073c2759f80ffc6d9ecee so now only the first panel should be open in a group (you can specify which panel you want to be open by setting `open` option of `startGroup`):

```php
echo $this->Panel->startGroup([
    'open' = false // All panels closed
]);
```

Note that for a lonely collapsible panel, I did not test it... The panel should be closed by default (not sure this will be the final behaviour, I'd preferred panels open by default outside groups but with an option to close them).

**Comment by nrother** [comment] 2016-07-12 15:58
I just noticed that **closed** panels have `aria-expanded=1`set in their initial state, were `false` (or at least `0` would be correct). It's fixed after clicking on any panel, though.

**Comment by Holt59** [comment] 2016-07-15 11:12
Tanks for pointing this out, this should be fixed by 9714eafcca8087b46d53b253791cff30ed4e274f.

**Comment by ypnos-web** [comment] 2016-09-28 14:45
I know this is kind of exotic, but I have a page where I add successive panels via AJAX calls (panels are fetched from the server). The problem is that when the user tries to collapse them, always the first panel gets collapsed.

This workaround solves the issue:
Replace https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/07e00290af09a1a50ee8ba708357b9af56c56e14/src/View/Helper/BootstrapPanelHelper.php#L125-L126 with:
```php
            $id = hash('md5', uniqid());
            $this->_headId = 'heading-'.$id;
            $this->_bodyId = 'collapse-'.$id;
```

Would you like to incorporate something like that?

**Comment by Holt59** [comment] 2016-09-29 06:31
I don't really like the id of hashing the id, but I could provide a way to specify the "panel counter" manually via an option, e.g.:

```php
$options += [
    'no-body'     => false,
    'type'        => 'default',
    'collapsible' => $this->config('collapsible'),
    'open'        => !$this->_groupInGroup,
    'count'       => $this->_panelCount
];
// ...
if ($this->_collapsible) {    
    $count = $options['count'];
    $this->_headId = 'heading-'.$count;
    $this->_bodyId = 'collapse-'.$count;
    $this->_panelCount = intval($count) + 1;
}
```

I will try to push something when I get back on a working computer! ;)

**Comment by ypnos-web** [comment] 2016-09-30 13:04
Great, I already submit a counter, so this would solve the problem for me!

**Comment by Holt59** [comment] 2016-09-30 13:25
I have pushed a fix for this that you can try to use. Let me know if you face any issue.

**Comment by Holt59** [comment] 2016-11-24 16:52
I am closing this issue since the Panel helper is in a stable working state now. Feel free to open new issues if you have problem with specific parts of the helper or you want some enhancements.

**Closed by Holt59** 2016-11-24 16:52 UTC
Labels: enhancement
